version: '3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: ${RESTART_POLYCY}
    volumes:
      - ./src:/usr/app/src
    networks:
      - my-net
    depends_on:
      - postgres
  postgres:
    container_name: 'postgres'
    build: ./database
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: ${RESTART_POLYCY}
    volumes:
      - .:/code
      - log:/app/log
      - db:/app/db
    networks:
      - my-net
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
networks:
  my-net:
    driver: bridge
volumes:
  log: {}
  db: {}
