version: '3'
services: 
    node: 
        build: .
        ports: 
            - ${PORT}:${PORT}
        restart: ${RESTART_POLYCY}
        # networks: 
        #     - back
        depends_on: 
            - postgres
    postgres:
        build: ./database
        ports: 
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        restart: ${RESTART_POLYCY}
        volumes:
            - .:/code
            - log:/app/log
            - db:/app/db
        # networks: 
        #     - back
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        depends_on: 
            - networks
    networks:
        build: ./network
volumes:
    log: {}
    db: {}

