version: '3'
services: 
    node: 
        build: .
        ports: 
            - ${PORT}:${PORT}
        image: demanikys/node
        restart: ${RESTART_POLYCY}
        networks: 
            - my-net
        depends_on: 
            - postgres
    postgres:
        build: ./database
        ports: 
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        image: demanikys/postgres
        restart: ${RESTART_POLYCY}
        volumes:
            - .:/code
            - log:/app/log
            - db:/app/db
        networks: 
            - my-net
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
networks:
    my-net:
volumes:
    log: {}
    db: {}

