version: '3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    image: demanikys/node
    restart: ${RESTART_POLYCY}
    networks:
      - my-net
    depends_on:
      - postgres
  postgres:
    build: ./database
    ports:
      - ${DB_PORT}:${DB_PORT}
    image: demanikys/postgres
    restart: ${RESTART_POLYCY}
    volumes:
      - .:/code
      - log:/app/log
      - db:/app/db
    networks:
      - my-net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
networks:
  my-net:
volumes:
  log: {}
  db: {}
